config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:new,:create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :name, length: {within: 3..255}
  validates :code, length: {is:3}, uniqueness: {case_sensitive:false}
  has_many :arrivals, class_name: 'Flight', foreign_key: 'arrival_airport_id'
  has_many :departures, class_name: 'Flight', foreign_key: 'departure_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, inverse_of: :booking
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name:  'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :passengers
  has_many :bookings

  def duration
    arriving - leaving
  end

  def duration=(duration)
    self.leaving = arriving + duration
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :flight
  belongs_to :booking

  validates :name, length: {in: 3..255}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, format: {with: VALID_EMAIL_REGEX}, length: {in: 1..255}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new(flight_id: params[:flight])

    params[:num_passengers].to_i.times {@booking.passengers.build(
      flight_id:@booking.flight_id)}

  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:info] = 'Booking confirmed'
      @booking.passengers.each do |p|
        PassengerMailer.with(passenger: p).thank_you.deliver_later
      end
      redirect_to booking_path(@booking)
    else
      flash.now[:error] = 'Details incorrect'
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id,
      passengers_attributes: [:name,:email,:flight_id])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @arrival_airports = @departure_airports = Airport.all
    @passengers = [['1',1],['2',2],['3',3],['4',4]]
    #@available_dates =  Flight.all.pluck(:leaving).uniq.sort
    @last_date = Flight.maximum(:leaving).to_date
    @flight_date = @first_date = Flight.minimum(:leaving).to_date
    @departure = @arrival = @arrival_airports.first

    if search = params[:flight]
      @num_passengers = params[:booking][:passengers]
      @flight_date = search[:leaving_date]
      @departure = search[:departure_airport_id]
      @arrival = search[:arrival_airport_id]

      @flights = Flight.where(
        departure_airport_id: @departure,
        arrival_airport_id: @arrival ).where(
          "CAST(leaving AS date) = ?", @flight_date
        ).order(:leaving)

      if @flights.empty?
        @flights =        Flight.where(
                departure_airport_id: @departure,
                arrival_airport_id: @arrival).where(
                  "CAST(leaving AS date) BETWEEN
                  (CAST(:leaving AS date) - INTERVAL'14 days') AND
                  (CAST(:leaving AS DATE) + INTERVAL'14 days')
                  ", leaving: @flight_date
                ).order(:leaving)
        if @flights.empty?
          flash.now[:warning] =
          'Sorry there are no flights between those airports.  Please try again.'
        else

          flash.now[:info] =
          'Sorry there are not flights for those dates.  Showing other dates within two weeks.'
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="row">
<div class=" offset-md-3 col-md-6">
<h1>Book your flight</h1>
<%= form_for @booking do |f| %>
  <%= render partial: 'shared/errors', locals: {object: @booking }%>
  <div class="form-group">
     <h5>Flight Details:</h5>
    Departing: <%= @booking.flight.departure_airport.name %>, at
      <%=@booking.flight.leaving %> <br>
    Arriving: <%= @booking.flight.arrival_airport.name %>, at
      <%= @booking.flight.arriving %>
  <%= f.hidden_field :flight_id %>
  </div>
    <% counter = 1 %>
    <h5>Please enter passenger details: </h5>
    <%= f.fields_for :passengers do |p| %>
      <div class="form-group">
        <%= p.label :name, 'Name:' %>
        <%= p.text_field :name, class: 'form-control',
          placeholder: "Passenger #{counter}"%>
        <%= p.label :email, 'Email:' %>
        <%= p.email_field :email, class: 'form-control',
          placeholder: "Passenger #{counter}" %>
        <%= p.hidden_field :flight_id %>
      </div>
      <% counter += 1 %>
    <% end %>

  <%= f.submit 'Confirm booking', class: 'btn btn-primary' %>
  <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>
Your Booking details</h1>

<p>
<strong>Your Booking Reference:</strong><%= @booking.id %> </p>

<p>
<strong>  Departing:</strong> <%= @booking.flight.departure_airport.name %><br>
On: <%= @booking.flight.leaving %>
</p>

<p>
<strong> Arriving: </strong> <%= @booking.flight.arrival_airport.name %><br>
On: <%= @booking.flight.arriving %>
</p>

<h3>Passengers</h3>
<%= render @booking.passengers %>

app/views/flights/_flight.hml.erb
<label class = "btn btn-secondary btn-block
<%="active" if @first %>" >
<%= radio_button_tag :flight, flight.id, checked = @first
%>

<%= flight.leaving.strftime("%d %b %Y %H:%M UTC") %>
-&gt &#9992

  &#9992 -&gt
  <%= flight.arriving.strftime("%d %b %Y %H:%M UTC") %>


</label>
<% @first = false %>

app/views/flights/_flight.html.erb
<label class = "btn btn-secondary btn-block
<%="active" if @first %>" >
<%= radio_button_tag :flight, flight.id, checked = @first
%>

<%= flight.leaving.strftime("%d %b %Y %H:%M UTC") %>
-&gt &#9992

  &#9992 -&gt
  <%= flight.arriving.strftime("%d %b %Y %H:%M UTC") %>


</label>
<% @first = false %>

app/views/flights/index.html.erb
<h1>Search for flights</h1>
<div class="row">
  <% if @flights  && !@flights.empty?
      position = 'col-md-4 offset-md-1'
  else
      position = 'col-md-6 offset-md-3'
  end
      %>
  <div class= "<%= position %>" >

<h4>1: Search</h4>
<%= form_tag root_path, method: 'get' do %>
  <div class="form-group">
  <%= label_tag 'flight[departure_airport_id]', 'Departing from:' %>
  <%= collection_select(:flight,:departure_airport_id,
    @departure_airports, :id, :name,{selected: @departure},
    {class:'form-control',
    }) %>
    </div>
    <div class="form-group">
  <%= label_tag 'flight[arrival_airport_id]', 'Arriving at:' %>
  <%= collection_select(:flight, :arrival_airport_id,
    @arrival_airports, :id, :name,{selected: @arrival}, {class:'form-control'}) %>
  </div>
  <div class="form-group">
  <%= label_tag 'booking[passengers]', 'Number of Passengers:' %>
  <%= select_tag('booking[passengers]',
   options_for_select(@passengers, selected = @num_passengers),
    class:'form-control' ) %>

    </div>
      <div class="form-group">
  <%= label_tag 'flight[leaving_date]', 'Date:' %>

  <%= date_field_tag('flight[leaving_date]', value = @flight_date,
      min: @first_date, max: @last_date, class: 'form-control') %>
  </div>
  <%= submit_tag "Search", class:"btn btn-primary" %>
  <br>
<% end %>
</div>
  <% if @flights  && !@flights.empty? %>

  <div class="col-md-6 col-md-offset-1">
    <h4>2. Choose your flight</h4>
    <div class="left-head">
      <strong>   From:</strong>
      <em>  <%= @flights.first.departure_airport.name %></em>
      (<%= @flights.first.departure_airport.code %>)
    </div>
    <div class="right-head">
      <strong> To:</strong>
      <em> <%= @flights.first.arrival_airport.name %> </em>
      (<%= @flights.first.arrival_airport.code %>)
    </div>


    <%= form_tag new_booking_path, method: 'get' do %>
    <div class= "btn-group-vertical btn-group-toggle form-group"
      data-toggle = "buttons">

      <% @first = true %>
      <%= render @flights %>

    </div>
    <%= hidden_field_tag :num_passengers, @num_passengers %>
    <%= submit_tag "Book #{@num_passengers} passengers",
    class:'btn btn-primary' %>
    <% end %>
  </div>
  <% end %>
</div>

<div display = 'block'> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsbooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>

    </div>
    <div class="container">
      <br> <br>
      <h3>Not a real flight booker</h3>
     
    </div>
    <div display = 'block'>
    <br><%= debug(params) if Rails.env.development? %>
<br><%= session.to_hash.inspect if Rails.env.development?  %>
    </div>
  </body>
</html>

app/views/shared/_errors-html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    This form contains <%= pluralize(object.errors.count, 'errors')%>:
    <ul>
    <% object.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    This form contains <%= pluralize(object.errors.count, 'errors')%>:
    <ul>
    <% object.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>